import { slugify } from "./utils";

export type StandardAiCategory = {
  name: string;
  slug: string;
  description: string;
  seoTitle: string;
  seoDescription: string;
  sortOrder: number;
  isFeatured: boolean;
};

export const STANDARD_AI_CATEGORIES: StandardAiCategory[] = [
  {
    name: "AI Writing",
    slug: "ai-writing",
    description: "AI tools for drafting, rewriting, summarizing, editing, and publishing written content.",
    seoTitle: "Best AI Writing Tools",
    seoDescription: "Discover AI writing tools for articles, marketing copy, emails, scripts, and everyday content workflows.",
    sortOrder: 0,
    isFeatured: true,
  },
  {
    name: "AI Chatbots",
    slug: "ai-chatbots",
    description: "AI chatbots and conversational assistants for support, personal productivity, and customer interactions.",
    seoTitle: "Best AI Chatbots",
    seoDescription: "Browse AI chatbot tools for conversations, assistants, customer chat, and workflow support.",
    sortOrder: 1,
    isFeatured: true,
  },
  {
    name: "AI Image",
    slug: "ai-image",
    description: "AI image tools for generation, editing, enhancement, and creative visual production.",
    seoTitle: "Best AI Image Tools",
    seoDescription: "Explore AI image tools for design assets, illustrations, photo editing, and visual content creation.",
    sortOrder: 2,
    isFeatured: true,
  },
  {
    name: "AI Video",
    slug: "ai-video",
    description: "AI video tools for generation, editing, avatars, clips, and multimedia storytelling.",
    seoTitle: "Best AI Video Tools",
    seoDescription: "Find AI video tools for generation, editing, avatars, repurposing, and production workflows.",
    sortOrder: 3,
    isFeatured: true,
  },
  {
    name: "AI Audio",
    slug: "ai-audio",
    description: "AI audio tools for speech, music, voice cloning, transcription, and sound production.",
    seoTitle: "Best AI Audio Tools",
    seoDescription: "Compare AI audio tools for voice, music, transcription, dubbing, and sound design.",
    sortOrder: 4,
    isFeatured: true,
  },
  {
    name: "AI Coding",
    slug: "ai-coding",
    description: "AI coding tools for code generation, debugging, review, pair programming, and developer workflows.",
    seoTitle: "Best AI Coding Tools",
    seoDescription: "Browse AI coding tools for software development, debugging, pair programming, and faster shipping.",
    sortOrder: 5,
    isFeatured: true,
  },
  {
    name: "AI SEO",
    slug: "ai-seo",
    description: "AI SEO tools for keyword research, optimization, audits, internal workflows, and organic growth.",
    seoTitle: "Best AI SEO Tools",
    seoDescription: "Discover AI SEO tools for research, content optimization, audits, and search growth workflows.",
    sortOrder: 6,
    isFeatured: true,
  },
  {
    name: "AI Marketing",
    slug: "ai-marketing",
    description: "AI marketing tools for campaigns, content production, funnels, ads, and growth execution.",
    seoTitle: "Best AI Marketing Tools",
    seoDescription: "Find AI marketing tools for campaigns, ad creatives, content production, and demand generation.",
    sortOrder: 7,
    isFeatured: true,
  },
  {
    name: "AI Productivity",
    slug: "ai-productivity",
    description: "AI productivity tools for notes, meetings, planning, summaries, and daily execution.",
    seoTitle: "Best AI Productivity Tools",
    seoDescription: "Explore AI productivity tools for planning, meetings, notes, summaries, and personal workflow management.",
    sortOrder: 8,
    isFeatured: true,
  },
  {
    name: "AI Design",
    slug: "ai-design",
    description: "AI design tools for interfaces, branding, creative direction, layouts, and visual systems.",
    seoTitle: "Best AI Design Tools",
    seoDescription: "Browse AI design tools for UI, branding, layouts, mockups, and creative production.",
    sortOrder: 9,
    isFeatured: false,
  },
  {
    name: "AI Business",
    slug: "ai-business",
    description: "AI business tools for operations, documents, planning, strategy, and internal workflows.",
    seoTitle: "Best AI Business Tools",
    seoDescription: "Compare AI business tools for operations, planning, documents, and company knowledge workflows.",
    sortOrder: 10,
    isFeatured: false,
  },
  {
    name: "AI Research",
    slug: "ai-research",
    description: "AI research tools for discovery, synthesis, reading, fact finding, and analysis.",
    seoTitle: "Best AI Research Tools",
    seoDescription: "Discover AI research tools for discovery, source review, synthesis, and analytical workflows.",
    sortOrder: 11,
    isFeatured: false,
  },
  {
    name: "AI Education",
    slug: "ai-education",
    description: "AI education tools for tutoring, study support, curriculum design, and learning content.",
    seoTitle: "Best AI Education Tools",
    seoDescription: "Find AI education tools for tutoring, study assistance, lesson design, and learning support.",
    sortOrder: 12,
    isFeatured: false,
  },
  {
    name: "AI Agents",
    slug: "ai-agents",
    description: "AI agent tools for autonomous tasks, orchestration, assistants, and multi-step execution.",
    seoTitle: "Best AI Agent Tools",
    seoDescription: "Browse AI agent tools for autonomous workflows, assistants, orchestration, and task execution.",
    sortOrder: 13,
    isFeatured: false,
  },
  {
    name: "AI Data",
    slug: "ai-data",
    description: "AI data tools for extraction, enrichment, spreadsheets, analytics, and structured workflows.",
    seoTitle: "Best AI Data Tools",
    seoDescription: "Explore AI data tools for extraction, enrichment, analysis, spreadsheets, and data operations.",
    sortOrder: 14,
    isFeatured: false,
  },
  {
    name: "AI Presentation",
    slug: "ai-presentation",
    description: "AI presentation tools for decks, proposals, storytelling, and visual communication.",
    seoTitle: "Best AI Presentation Tools",
    seoDescription: "Compare AI presentation tools for decks, proposals, storytelling, and slide creation.",
    sortOrder: 15,
    isFeatured: false,
  },
  {
    name: "AI Social Media",
    slug: "ai-social-media",
    description: "AI social media tools for posts, scheduling, repurposing, engagement, and channel growth.",
    seoTitle: "Best AI Social Media Tools",
    seoDescription: "Discover AI social media tools for posts, scheduling, repurposing, and engagement workflows.",
    sortOrder: 16,
    isFeatured: false,
  },
  {
    name: "AI Customer Support",
    slug: "ai-customer-support",
    description: "AI customer support tools for tickets, chat, help centers, service automation, and knowledge workflows.",
    seoTitle: "Best AI Customer Support Tools",
    seoDescription: "Find AI customer support tools for ticketing, chat, automation, and support knowledge bases.",
    sortOrder: 17,
    isFeatured: false,
  },
  {
    name: "AI Developer Tools",
    slug: "ai-developer-tools",
    description: "AI developer tools for APIs, testing, observability, infrastructure, and engineering workflows.",
    seoTitle: "Best AI Developer Tools",
    seoDescription: "Browse AI developer tools for APIs, testing, infrastructure, observability, and engineering teams.",
    sortOrder: 18,
    isFeatured: false,
  },
  {
    name: "AI Automation",
    slug: "ai-automation",
    description: "AI automation tools for app connections, workflows, agents, triggers, and repetitive task reduction.",
    seoTitle: "Best AI Automation Tools",
    seoDescription: "Explore AI automation tools for workflows, app connections, triggers, and repetitive process automation.",
    sortOrder: 19,
    isFeatured: false,
  },
];

const CATEGORY_ALIAS_MAP: Record<string, string[]> = {
  "ai-writing": ["ai-writing"],
  writing: ["ai-writing"],
  "ai writing": ["ai-writing"],
  "ai-chatbots": ["ai-chatbots"],
  chatbots: ["ai-chatbots"],
  chatbot: ["ai-chatbots"],
  "ai chatbots": ["ai-chatbots"],
  "ai-image": ["ai-image"],
  image: ["ai-image"],
  "image generation": ["ai-image"],
  "ai image": ["ai-image"],
  "image-generation": ["ai-image"],
  "ai-video": ["ai-video"],
  video: ["ai-video"],
  "ai video": ["ai-video"],
  "ai-audio": ["ai-audio"],
  audio: ["ai-audio"],
  "ai audio": ["ai-audio"],
  "video-audio": ["ai-video", "ai-audio"],
  "video & audio": ["ai-video", "ai-audio"],
  "video and audio": ["ai-video", "ai-audio"],
  multimedia: ["ai-video", "ai-audio"],
  "ai-coding": ["ai-coding"],
  code: ["ai-coding"],
  coding: ["ai-coding"],
  "code assistant": ["ai-coding"],
  "ai coding": ["ai-coding"],
  "ai-seo": ["ai-seo"],
  seo: ["ai-seo"],
  "ai seo": ["ai-seo"],
  "ai-marketing": ["ai-marketing"],
  marketing: ["ai-marketing"],
  "ai marketing": ["ai-marketing"],
  "ai-productivity": ["ai-productivity"],
  productivity: ["ai-productivity"],
  "ai productivity": ["ai-productivity"],
  "ai-design": ["ai-design"],
  design: ["ai-design"],
  "ai design": ["ai-design"],
  "ai-business": ["ai-business"],
  business: ["ai-business"],
  "ai business": ["ai-business"],
  sales: ["ai-business"],
  finance: ["ai-business"],
  hr: ["ai-business"],
  legal: ["ai-business"],
  recruiting: ["ai-business"],
  "e-commerce": ["ai-business"],
  ecommerce: ["ai-business"],
  "ai-research": ["ai-research"],
  research: ["ai-research"],
  "ai research": ["ai-research"],
  "ai-education": ["ai-education"],
  education: ["ai-education"],
  "ai education": ["ai-education"],
  "ai-agents": ["ai-agents"],
  agents: ["ai-agents"],
  "ai agents": ["ai-agents"],
  "ai-data": ["ai-data"],
  data: ["ai-data"],
  "ai data": ["ai-data"],
  "data analysis": ["ai-data"],
  "ai-presentation": ["ai-presentation"],
  presentation: ["ai-presentation"],
  presentations: ["ai-presentation"],
  "ai presentation": ["ai-presentation"],
  "ai-social-media": ["ai-social-media"],
  "social media": ["ai-social-media"],
  social: ["ai-social-media"],
  "ai social media": ["ai-social-media"],
  "ai-customer-support": ["ai-customer-support"],
  "customer support": ["ai-customer-support"],
  support: ["ai-customer-support"],
  "ai customer support": ["ai-customer-support"],
  "ai-developer-tools": ["ai-developer-tools"],
  "developer tools": ["ai-developer-tools"],
  developers: ["ai-developer-tools"],
  "ai developer tools": ["ai-developer-tools"],
  "ai-automation": ["ai-automation"],
  automation: ["ai-automation"],
  "ai automation": ["ai-automation"],
  translation: ["ai-writing"],
};

const STANDARD_CATEGORY_MAP = new Map(STANDARD_AI_CATEGORIES.map((item) => [item.slug, item]));

export function getStandardAiCategoryBySlug(slug: string) {
  return STANDARD_CATEGORY_MAP.get(slug);
}

export function normalizeAiCategoryKey(input: string) {
  return slugify(input).replace(/-/g, " ").trim();
}

export function resolveCanonicalCategorySlugs(input: string): string[] {
  const normalizedKey = normalizeAiCategoryKey(input);
  return CATEGORY_ALIAS_MAP[normalizedKey] ?? [];
}

export function resolveCanonicalCategorySlug(input: string): string | null {
  return resolveCanonicalCategorySlugs(input)[0] ?? null;
}
